name: Chrome Remote Desktop

on:
  workflow_dispatch:

jobs:
  crd:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Restore Files
      uses: actions/cache@v3
      with:
        path: |
          ~/workdir
          ~/Desktop
          ~/Documents
          ~/Downloads
          ~/Pictures
          ~/Videos
          ~/Music
          ~/.config
          ~/.local/share
          ~/tools
          ~/projects
        key: mydata-${{ github.run_id }}
        restore-keys: |
          mydata-

    - name: Install XFCE Desktop
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils wget curl

    - name: Install Chrome Remote Desktop
      run: |
        wget -q https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo apt-get update -y
        sudo apt-get install -y ./chrome-remote-desktop_current_amd64.deb

    - name: Setup Desktop
      run: |
        echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session
        sudo groupadd chrome-remote-desktop || true
        sudo usermod -aG chrome-remote-desktop $USER

    - name: Start CRD
      run: |
        DISPLAY= /opt/google/chrome-remote-desktop/start-host \
        --code="4/0AeoWuM_sW4iXJnzU-qnq68dK4aemQMrupZ_-QDmWKfVTJAjw0V154OLU78F0e5TB54SECg" \
        --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
        --name=$(hostname)

        sudo systemctl restart chrome-remote-desktop@$USER || true

    - name: Keep Alive
      run: sleep 21000

    - name: Save Files
      if: always()
      uses: actions/cache@v3
      with:
        path: |
          ~/workdir
          ~/Desktop
          ~/Documents
          ~/Downloads
          ~/Pictures
          ~/Videos
          ~/Music
          ~/.config
          ~/.local/share
          ~/tools
          ~/projects
        key: mydata-${{ github.run_id }}
